# Generated by Django 5.2.9 on 2025-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('event_url', models.URLField()),
            ],
        ),
    ]
